# Generated by Django 2.1.7 on 2019-03-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sessionLevels',
            new_name='sessionLevel',
        ),
    ]
