# Generated by Django 2.1.7 on 2019-03-19 09:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190319_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BankUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=30)),
                ('registered_data', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bankUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.BankUser'),
        ),
    ]
